# Generated by Django 3.2 on 2021-04-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat_count',
            field=models.IntegerField(default=0),
        ),
    ]
